force-app/main/default/objects/Navigation__c/Navigation__c.object-meta.xml
<CustomObject>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Navigation__c/fields/List_View_Name__c.field-meta.xml
<CustomField>
    <fullName>List_View_Name__c</fullName>
    <label>List View Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation__c/fields/List_View_Object__c.field-meta.xml
<CustomField>
    <fullName>List_View_Object__c</fullName>
    <label>List View Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Navigation__c</referenceTo>
    <relationshipLabel>Navigation</relationshipLabel>
    <relationshipName>Parent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Navigation__c/fields/Quick_Create_Object__c.field-meta.xml
<CustomField>
    <fullName>Quick_Create_Object__c</fullName>
    <label>Action Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_navatarEdgeMenuCntlr.cls
/* 
New Implimentation:
Developer       :   Sameeksha Sahu
Project         :   Navigation & SDG 
Date            :   08/August/2019
*/
@isTest
public class Test_navatarEdgeMenuCntlr {

    static testmethod void TestnavatarEdgeMenuCntlr()
    {
        Navigation__c nav1 = new Navigation__c(Name='TestNav',Quick_Create_Object__c='Account',List_View_Object__c='Account',List_View_Name__c='fsg');
        insert nav1;
        Navigation__c nav2 = new Navigation__c(Name='TestNav1',Quick_Create_Object__c='Account', URL__c='https://www.google.com');
        insert nav2;
        Navigation__c nav3 = new Navigation__c(Name='TestNav',Quick_Create_Object__c='Account',List_View_Object__c='Account');
        insert nav3;
        Navigation__c nav4 = new Navigation__c(Name='TestNav',Quick_Create_Object__c='Account',List_View_Object__c='Account',Parent__c=nav3.id);
        insert nav4;
        test.startTest();
        string json = 'abc';
        map<String,String> mapURL = new map<String,String>();
        mapURL.put('Con','Abdgjg');
        navatarEdgeMenuCntlr navEdgeClass = new navatarEdgeMenuCntlr();
        navatarEdgeMenuCntlr.responseWrapper testWrap = new navatarEdgeMenuCntlr.responseWrapper(); 
        testWrap.jsonStr = json;
        testWrap.mapIdToUrl = mapURL;
        navatarEdgeMenuCntlr.getJson('New Relationship');
        navatarEdgeMenuCntlr.getJson(''); // added to increase test coverage PEv4.7 by Aditya 26 April 2021
        system.assertEquals('TestNav',nav1.Name); // added for security issue PEv4.7 by Aditya on 23 March 2021
        Test.stopTest();
    }
    
}